version: "3.8"

services:
    api:
        build:
            context: .
            dockerfile: Api/Dockerfile
        ports:
            - "5000:8080"
        environment:
            SETTINGS__SECOND_API_URL: http://api2:8082/
            ASPNETCORE_HTTP_PORTS: 8080
    api2:
        build:
            context: .
            dockerfile: Api2/Dockerfile
        ports:
            - "5051:8082"
        environment:
           ASPNETCORE_URLS: "http://0.0.0.0:8082"    
           ASPNETCORE_HTTP_PORTS: 8082
        