apiVersion: apps/v1
kind: Deployment
metadata:
  name: api2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api2
  template:
    metadata:
      labels:
        app: api2
    spec:
      imagePullSecrets:
      - name: harbor-regcred
      containers:
      - name: api2
        image: harbor.local:83/api-service/api2:v2
        ports:
        - containerPort: 8082
        env:
        - name: ASPNETCORE_URLS
          value: "http://0.0.0.0:8082"
        - name: ASPNETCORE_HTTP_PORTS
          value: "8082"
---
apiVersion: v1
kind: Service
metadata:
  name: api2
spec:
  selector:
    app: api2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8082
  type: ClusterIP
